<?php
require_once 'db_config.php';

// Constants
define('REGISTRATION_FEE', 500.00);

// User Management Functions
function getUsers() {
    try {
        $conn = getDbConnection();
        if (!$conn) {
            throw new Exception("Database connection failed");
        }

        $stmt = $conn->query("SELECT * FROM hazle_users ORDER BY registrationDate DESC");
        return $stmt->fetchAll(PDO::FETCH_ASSOC);
    } catch (Exception $e) {
        error_log("Error getting users: " . $e->getMessage());
        return [];
    }
}

function saveUser($userData) {
    try {
        $conn = getDbConnection();
        if (!$conn) {
            throw new Exception("Database connection failed");
        }

        // Begin transaction
        $conn->beginTransaction();

        // First insert without studentId to get the auto-incremented ID
        $stmt = $conn->prepare("
            INSERT INTO hazle_users (
                name, email, password, phone, 
                collegeName, collegeCity, collegeState, 
                mockScore, mockRank
            ) VALUES (
                :name, :email, SHA2(:password, 256), :phone,
                :collegeName, :collegeCity, :collegeState,
                :mockScore, :mockRank
            )
        ");

        // Generate random mock score and rank
        $mockScore = rand(0, 100);
        $mockRank = rand(1, 500);

        $result = $stmt->execute([
            ':name' => $userData['name'],
            ':email' => $userData['email'],
            ':password' => $userData['password'],
            ':phone' => $userData['phone'],
            ':collegeName' => $userData['collegeName'],
            ':collegeCity' => $userData['collegeCity'],
            ':collegeState' => $userData['collegeState'],
            ':mockScore' => $mockScore,
            ':mockRank' => $mockRank
        ]);

        if ($result) {
            // Since studentId is populated by the DB trigger, commit and then fetch the created record
            $id = $conn->lastInsertId();
            $conn->commit();

            // Retrieve the inserted user row (including studentId generated by trigger)
            $fetch = $conn->prepare("SELECT * FROM hazle_users WHERE id = :id");
            $fetch->execute([':id' => $id]);
            $user = $fetch->fetch(PDO::FETCH_ASSOC);

            return $user ?: true;
        }

        $conn->rollBack();
        return false;
    } catch (Exception $e) {
        error_log("Error saving user: " . $e->getMessage());
        return false;
    }
}

function isPasswordStrong($password) {
    // Stronger checks: min length 8, contains a digit, contains a letter, contains uppercase and special char
    if (strlen($password) < 8) return false;
    if (!preg_match('/[0-9]/', $password)) return false;
    if (!preg_match('/[A-Za-z]/', $password)) return false;
    if (!preg_match('/[A-Z]/', $password)) return false;
    if (!preg_match('/[^A-Za-z0-9]/', $password)) return false;
    return true;
}

function findUser($identifier, $password) {
    try {
        $conn = getDbConnection();
        if (!$conn) {
            throw new Exception("Database connection failed");
        }

        // First check if the account is locked
        $checkLock = $conn->prepare("
            SELECT login_attempts, status, TIMESTAMPDIFF(MINUTE, last_login_attempt, NOW()) as minutes_since_last_attempt 
            FROM hazle_users 
            WHERE (email = :identifier OR studentId = :identifier)
        ");
        $checkLock->execute([':identifier' => $identifier]);
        $lockInfo = $checkLock->fetch(PDO::FETCH_ASSOC);

        if ($lockInfo) {
            // Reset attempts if it's been more than 30 minutes
            if ($lockInfo['minutes_since_last_attempt'] > 30) {
                $resetAttempts = $conn->prepare("
                    UPDATE hazle_users 
                    SET login_attempts = 0, 
                        status = 'active' 
                    WHERE (email = :identifier OR studentId = :identifier)
                ");
                $resetAttempts->execute([':identifier' => $identifier]);
                $lockInfo['login_attempts'] = 0;
                $lockInfo['status'] = 'active';
            }
            
            // Check if account is blocked
            if ($lockInfo['status'] === 'blocked') {
                throw new Exception("Account is locked. Please try again later or contact support.");
            }
        }

        // Check credentials
        $stmt = $conn->prepare("
            SELECT * FROM hazle_users 
            WHERE (email = :identifier OR studentId = :identifier)
            AND password = SHA2(:password, 256)
            AND status = 'active'
        ");

        $stmt->execute([
            ':identifier' => $identifier,
            ':password' => $password
        ]);

        $user = $stmt->fetch(PDO::FETCH_ASSOC);

        // Update login attempts
        if (!$user) {
            $attempts = ($lockInfo['login_attempts'] ?? 0) + 1;
            $updateAttempts = $conn->prepare("
                UPDATE hazle_users 
                SET login_attempts = :attempts,
                    last_login_attempt = NOW(),
                    status = CASE WHEN :attempts >= 3 THEN 'blocked' ELSE status END
                WHERE (email = :identifier OR studentId = :identifier)
            ");
            $updateAttempts->execute([
                ':attempts' => $attempts,
                ':identifier' => $identifier
            ]);

            if ($attempts >= 3) {
                throw new Exception("Account has been locked due to too many failed attempts.");
            }
        } else {
            // Reset attempts on successful login
            $resetAttempts = $conn->prepare("
                UPDATE hazle_users 
                SET login_attempts = 0,
                    last_login_attempt = NOW()
                WHERE id = :id
            ");
            $resetAttempts->execute([':id' => $user['id']]);
        }

        return $user;
    } catch (Exception $e) {
        error_log("Error finding user: " . $e->getMessage());
        return null;
    }
}

function isEmailOrStudentIdTaken($email, $studentId) {
    try {
        $conn = getDbConnection();
        if (!$conn) {
            throw new Exception("Database connection failed");
        }

        $stmt = $conn->prepare("
            SELECT COUNT(*) FROM hazle_users 
            WHERE email = :email OR studentId = :studentId
        ");

        $stmt->execute([
            ':email' => $email,
            ':studentId' => $studentId
        ]);

        return $stmt->fetchColumn() > 0;
    } catch (Exception $e) {
        error_log("Error checking duplicates: " . $e->getMessage());
        return true; // Safer to return true on error
    }
}

// Admin Functions
function validateAdmin($username, $password) {
    try {
        $conn = getDbConnection();
        if (!$conn) {
            throw new Exception("Database connection failed");
        }

        // Check if account is locked
        $checkLock = $conn->prepare("
            SELECT login_attempts, status, TIMESTAMPDIFF(MINUTE, last_login_attempt, NOW()) as minutes_since_last_attempt 
            FROM hazle_admins 
            WHERE username = :username
        ");
        $checkLock->execute([':username' => $username]);
        $lockInfo = $checkLock->fetch(PDO::FETCH_ASSOC);

        if ($lockInfo) {
            // Reset attempts if it's been more than 30 minutes
            if ($lockInfo['minutes_since_last_attempt'] > 30) {
                $resetAttempts = $conn->prepare("
                    UPDATE hazle_admins 
                    SET login_attempts = 0, 
                        status = 'active' 
                    WHERE username = :username
                ");
                $resetAttempts->execute([':username' => $username]);
                $lockInfo['login_attempts'] = 0;
                $lockInfo['status'] = 'active';
            }
            
            if ($lockInfo['status'] === 'blocked') {
                throw new Exception("Account is locked. Please try again later or contact support.");
            }
        }

        $stmt = $conn->prepare("
            SELECT * FROM hazle_admins 
            WHERE username = :username 
            AND password = SHA2(:password, 256)
            AND status = 'active'
        ");

        $stmt->execute([
            ':username' => $username,
            ':password' => $password
        ]);

        $admin = $stmt->fetch(PDO::FETCH_ASSOC);
        
        if ($admin) {
            // Reset attempts and update last login on success
            $updateStmt = $conn->prepare("
                UPDATE hazle_admins 
                SET login_attempts = 0,
                    lastLogin = CURRENT_TIMESTAMP,
                    last_login_attempt = NOW()
                WHERE id = :id
            ");
            $updateStmt->execute([':id' => $admin['id']]);
            return true;
        } else {
            // Increment attempts on failure
            $attempts = ($lockInfo['login_attempts'] ?? 0) + 1;
            $updateAttempts = $conn->prepare("
                UPDATE hazle_admins 
                SET login_attempts = :attempts,
                    last_login_attempt = NOW(),
                    status = CASE WHEN :attempts >= 3 THEN 'blocked' ELSE status END
                WHERE username = :username
            ");
            $updateAttempts->execute([
                ':attempts' => $attempts,
                ':username' => $username
            ]);

            if ($attempts >= 3) {
                throw new Exception("Account has been locked due to too many failed attempts.");
            }
        }
        
        return false;
    } catch (Exception $e) {
        error_log("Error validating admin: " . $e->getMessage());
        return false;
    }
}

// Error logging function
function logError($message, $data = null) {
    error_log(sprintf(
        "[%s] Error: %s | Data: %s",
        date('Y-m-d H:i:s'),
        $message,
        $data ? json_encode($data) : 'none'
    ));
}

// API Endpoints
header('Content-Type: application/json');

try {
    $input = file_get_contents('php://input');
    $data = json_decode($input, true);
    
    if (!isset($data['action'])) {
        throw new Exception('No action specified');
    }

    switch ($data['action']) {
        case 'register':
            $data = json_decode(file_get_contents('php://input'), true);

                // Server-side validation with field-specific errors
                $errors = [];

                if (
                    isset($data['password']) && isset($data['confirm_password']) &&
                    $data['confirm_password'] !== '' &&
                    $data['password'] !== $data['confirm_password']
                ) {
                    $errors['confirm_password'] = ['code' => 'password_mismatch', 'message' => 'Passwords do not match'];
                }

                // Enforce minimum password strength
                if (isset($data['password']) && !isPasswordStrong($data['password'])) {
                    $errors['password'] = ['code' => 'password_weak', 'message' => 'Password must be at least 8 characters and include uppercase, number and special char'];
                }

                // Basic server-side email validation
                if (!isset($data['email']) || !filter_var($data['email'], FILTER_VALIDATE_EMAIL)) {
                    $errors['email'] = ['code' => 'invalid_email', 'message' => 'Invalid email address'];
                } else {
                    // studentId is generated by the database trigger; only check email for duplicates
                    if (isEmailOrStudentIdTaken($data['email'], null)) {
                        $errors['email'] = ['code' => 'email_taken', 'message' => 'Email already registered'];
                    }
                }

                // Phone validation: digits only, 7-15 characters
                if (!isset($data['phone']) || !preg_match('/^[0-9]{7,15}$/', $data['phone'])) {
                    $errors['phone'] = ['code' => 'invalid_phone', 'message' => 'Phone must be 7-15 digits'];
                }

                // Remove confirmation before further processing
                unset($data['confirm_password']);

                if (!empty($errors)) {
                    echo json_encode(['success' => false, 'errors' => $errors]);
                    exit;
                }

            $userData = array_merge($data, [
                'registrationDate' => date('Y-m-d H:i:s'),
                'mockScore' => rand(0, 100),
                'mockRank' => rand(1, 500)
            ]);

            $created = saveUser($userData);
            if ($created) {
                // If saveUser returned the created user row, include it in the response
                if (is_array($created)) {
                    echo json_encode(['success' => true, 'message' => 'Registration successful', 'user' => $created]);
                } else {
                    echo json_encode(['success' => true, 'message' => 'Registration successful']);
                }
            } else {
                echo json_encode(['success' => false, 'message' => 'Registration failed']);
            }
            break;
            
        case 'login':
            $data = json_decode(file_get_contents('php://input'), true);
            
            // Input validation
            if (!isset($data['identifier']) || !isset($data['password'])) {
                echo json_encode([
                    'success' => false, 
                    'message' => 'Missing credentials'
                ]);
                break;
            }

            logError('Login attempt', ['identifier' => $data['identifier']]);
            $user = findUser($data['identifier'], $data['password']);
            
            if ($user) {
                logError('Login successful', ['user' => $user['studentId']]);
                echo json_encode([
                    'success' => true, 
                    'user' => $user,
                    'message' => 'Login successful'
                ]);
            } else {
                logError('Login failed', ['identifier' => $data['identifier']]);
                echo json_encode([
                    'success' => false, 
                    'message' => 'Invalid email/ID or password'
                ]);
            }
            break;
            
        case 'admin_login':
            // Input validation
            if (!isset($data['username']) || !isset($data['password'])) {
                echo json_encode([
                    'success' => false, 
                    'message' => 'Missing credentials'
                ]);
                break;
            }
            
            if (validateAdmin($data['username'], $data['password'])) {
                echo json_encode(['success' => true, 'message' => 'Admin login successful']);
            } else {
                echo json_encode(['success' => false, 'message' => 'Invalid admin credentials']);
            }
            break;
            
        case 'get_users':
            $data = json_decode(file_get_contents('php://input'), true);
            if (isset($data['admin']) && $data['admin'] === true) {
                echo json_encode(['success' => true, 'users' => getUsers()]);
            } else {
                echo json_encode(['success' => false, 'message' => 'Unauthorized']);
            }
            break;
            
        default:
            echo json_encode(['success' => false, 'message' => 'Invalid action']);
    }
} catch (Exception $e) {
    logError($e->getMessage(), isset($data) ? $data : null);
    echo json_encode([
        'success' => false,
        'message' => 'An error occurred: ' . $e->getMessage(),
        'debug' => [
            'input' => isset($input) ? $input : null,
            'parsed' => isset($data) ? $data : null
        ]
    ]);
}
?>